$bootstrapscript = <<-SCRIPT
set -euxvo pipefail
echo ">>>>>>>>>>>>> Installing the UI..."
yum -y update
yum install -y xorg-x11*
yum install -y gdm

amazon-linux-extras install -y mate-desktop1.x

bash -c 'echo PREFERRED=/usr/bin/mate-session > /etc/sysconfig/desktop'

echo ">>>>>>>>>>>>>>>> Adding samurai user"
useradd -m samurai -G wheel

echo samurai:samurai | chpasswd

echo ">>>>>>>>>>>>>>>> Install Firefox"
wget -O /tmp/firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US"
pushd /tmp
tar xjf firefox.tar.bz2
mv firefox/ /opt
ln -s /opt/firefox/firefox /usr/bin/firefox
wget https://raw.githubusercontent.com/mozilla/sumo-kb/main/install-firefox-linux/firefox.desktop -P /usr/local/share/applications
mkdir -p /opt/firefox/browser/defaults/preferences/
ff_preferences="/opt/firefox/browser/defaults/preferences/all-samurai.js"
touch $ff_preferences
echo "pref('browser.startup.homepage', 'https://katana.test:8443');" >> $ff_preferences

echo ">>>>>>>>>>>>>>>> Installing Ansible and Git"
amazon-linux-extras install -y ansible2
yum install -y git

echo ">>>>>>>>>>>>>>>> Running Playbook"
pushd /vagrant
ansible-playbook -K amazon-linux/local_playbook.yml --extra-vars "groupname=samurai username=samurai"
popd

echo ">>>>>>>>>>>>>>>> Initializing certificates"
openssl genrsa -out /etc/samurai.d/certs/rootCAKey.pem 2048
openssl req -x509 -sha256 -new -nodes -key /etc/samurai.d/certs/rootCAKey.pem -days 365 -out /etc/samurai.d/certs/rootCACert.pem -subj "/C=US/ST=Hacking/L=Springfield/O=SamuraiWTF/CN=samuraiwtf"
cp /etc/samurai.d/certs/rootCACert.pem /etc/pki/ca-trust/source/anchors/
update-ca-trust
openssl req -new -newkey rsa:4096 -nodes -keyout /etc/samurai.d/certs/katana.test.key -out /etc/samurai.d/certs/katana.test.csr -subj "/C=US/ST=Hacking/L=Springfield/O=SamuraiWTF/CN=katana.test"

echo ">>>>>>>>>>>>>>>> Installing Katana"
katana --update
katana install katana
systemctl enable samurai-katana
katana start katana
SCRIPT


Vagrant.configure("2") do |config|

  config.vm.box = "gbailey/amzn2"

   config.vm.define "samuraiwtf", primary: true do |samuraiwtf|
    samuraiwtf.vm.host_name = "SamuraiWTF"
    samuraiwtf.vm.synced_folder "..", "/vagrant"

    samuraiwtf.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      vb.name = "SamuraiWTF-5.2"
    # Customize the amount of memory on the VM:
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--vrde", "off"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
    end

    samuraiwtf.vm.provision "shell", inline: $bootstrapscript
  end
end
