katana install zap
katana install burpsuite
katana install wordlists
katana install sqlmap
katana install nikto
katana install juice-shop
katana install wayfarer
katana install mutillidae
katana install dvwa
katana install samurai-dojo
katana install musashi