# -*- mode: ruby -*-
# vi: set ft=ruby :

$bootstrapscript = <<-SCRIPT
set -euxvo pipefail

# Set noninteractive mode for apt
export DEBIAN_FRONTEND=noninteractive

echo ">>>>>>>>>>>>> Installing prerequisites..."
apt-get update

# Install basic tools
apt install git curl wget -y
apt install ansible git -y

echo ">>>>>>>>>>>>>>>> Running Playbook"
pushd /vagrant
ansible-playbook -K ubuntu-2404/local_playbook.yml
popd

# echo ">>>>>>>>>>>>>>>> Update Firefox Prefs"
# ff_preferences="/etc/firefox/syspref.js"
# touch $ff_preferences
# echo "pref('browser.startup.homepage', 'https://katana.test:8443');" >> $ff_preferences

echo ">>>>>>>>>>>>>>>> Setting up Katana"
su - samurai -c 'katana cert init'

# Make root CA easily accessible for manual browser import
su - samurai -c 'katana cert export /opt/samurai/SamuraiWTF_Root_CA.crt'

# Trust the Katana CA system-wide (curl, apt, etc.)
cp /opt/samurai/SamuraiWTF_Root_CA.crt /usr/local/share/ca-certificates/samuraiwtf-katana-ca.crt
update-ca-certificates

katana setup-proxy
katana dns sync --all

echo ">>>>>>>>>>>>>>>> Installing Katana proxy service"
tee /etc/systemd/system/samurai-katana.service > /dev/null <<'UNIT'
[Unit]
Description=Katana Proxy Server
After=docker.service
Requires=docker.service

[Service]
Type=simple
User=samurai
WorkingDirectory=/home/samurai
Environment="HOME=/home/samurai"
ExecStart=/usr/bin/katana proxy start
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable samurai-katana
systemctl start samurai-katana

SCRIPT

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/ubuntu-desktop-2404-lts"

  # Disable automatic box update checking to speed up startup
  config.vm.box_check_update = false

  config.vm.define "samuraiwtf", primary: true do |samuraiwtf|
      samuraiwtf.vm.host_name = "SamuraiWTF"
      samuraiwtf.vm.synced_folder "..", "/vagrant", type: "rsync", rsync_exclude: ".git/"

      samuraiwtf.vm.provider "hyperv" do |hv|
        hv.vmname = "SamuraiWTF-7.0"
        hv.maxmemory = "4096"
        hv.cpus = "2" 
        hv.enable_virtualization_extensions = true
        hv.vm_integration_services = {
            guest_service_interface: true
            }
       end

      samuraiwtf.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.name = "SamuraiWTF-7.0"
        vb.memory = "4096"
        vb.customize ["modifyvm", :id, "--vram", "128"]
        vb.customize ["modifyvm", :id, "--cpus", "2"]
        vb.customize ["modifyvm", :id, "--vrde", "off"]
        vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
        vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
      end

      samuraiwtf.vm.provider "vmware_desktop" do |v|
        v.vmx["name"] = "SamuraiWTF-7.0"
        v.vmx["memsize"] = "4096"
        v.vmx["numvcpus"] = "2"
        v.vmx["cpuid.coresPerSocket"] = "1"
        v.gui = true
       end      
  end

  
  config.vm.provision "shell", inline: $bootstrapscript
end
