$bootstrapscript = <<-SCRIPT
echo ">>>>>>>>>>>>> Installing the UI..."
yum -y update
amazon-linux-extras install mate-desktop1.x -y
bash -c 'echo PREFERRED=/usr/bin/mate-session > /etc/sysconfig/desktop'
amazon-linux-extras install ansible2 -y
yum install -y git
git clone --depth=1 --single-branch --branch "5.0-dev" https://github.com/SamuraiWTF/samuraiwtf.git /tmp/samuraiwtf
pushd /tmp/samuraiwtf
ansible-playbook -K base/amazon-linux/vagrant_playbook.yml
katana --update
katana install katana
systemctl enable samurai-katana
katana start katana
SCRIPT


Vagrant.configure("2") do |config|

  config.vm.box = "bento/amazonlinux-2"

 
   config.vm.define "samuraiwtf", primary: true do |samuraiwtf|
    samuraiwtf.vm.host_name = "SamuraiWTF"    

    samuraiwtf.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      vb.name = "SamuraiWTF-5"
    # Customize the amount of memory on the VM:
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]    

    end

    samuraiwtf.vm.provision "shell", inline: $bootstrapscript
  end
end
