$bootstrapscript = <<-SCRIPT
echo ">>>>>>>>>>>>> Installing the UI..."
yum -y update
yum install -y xorg-x11*


amazon-linux-extras install -y mate-desktop1.x

bash -c 'echo PREFERRED=/usr/bin/mate-session > /etc/sysconfig/desktop'

echo ">>>>>>>>>>>>>>>> Adding user"
useradd -m samurai

echo samurai:samurai | chpasswd

echo ">>>>>>>>>>>>>>>>> Install Firefox"
wget -O /tmp/firefox.tar.bz2 "https://download.mozilla.org/?product=firefox-latest-ssl&os=linux64&lang=en-US"
pushd /tmp
tar xjf firefox.tar.bz2
mv firefox/ /opt
ln -s /opt/firefox/firefox /usr/bin/firefox
wget https://raw.githubusercontent.com/mozilla/sumo-kb/main/install-firefox-linux/firefox.desktop -P /usr/local/share/applications
ff_preferences="/opt/firefox/browser/defaults/preferences/all-samurai.js"
touch $ff_preferences
echo "pref('browser.startup.homepage', 'https://katana.test');" >> $ff_preferences

echo ">>>>>>>>>>>>>>>> Installing Ansible and Git"

amazon-linux-extras install -y ansible2
git clone --depth=1 --single-branch --branch="updates/2022-03-vm-updates" https://github.com/SamuraiWTF/samuraiwtf.git /tmp/samuraiwtf

pushd /tmp/samuraiwtf
# ansible-playbook -K base/amazon-linux/vagrant_playbook.yml --extra-vars "groupname=samurai"
# katana --update
# katana install katana
# systemctl enable samurai-katana
# katana start katana
SCRIPT


Vagrant.configure("2") do |config|

  config.vm.box = "gbailey/amzn2"

 
   config.vm.define "samuraiwtf", primary: true do |samuraiwtf|
    samuraiwtf.vm.host_name = "SamuraiWTF"    

    samuraiwtf.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
      vb.gui = true
      vb.name = "SamuraiWTF-5.2"
    # Customize the amount of memory on the VM:
      vb.memory = "4096"
      vb.customize ["modifyvm", :id, "--vram", "128"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
      vb.customize ["modifyvm", :id, "--vrde", "off"]
      vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]

#       config.vm.network "private_network", :type => 'dhcp', :adapter => 2
    end

    samuraiwtf.vm.provision "shell", inline: $bootstrapscript
  end
end
